### ISSUE TITLE
Default codec is json, not plain

### ISSUE THREAD

**Issue by akking** [logstash-plugins/logstash-input-rabbitmq#102]
I think the default codec for this plugin is "json"[(souce)](https://github.com/logstash-plugins/logstash-input-rabbitmq/blob/master/lib/logstash/inputs/rabbitmq.rb#L103), not "plain" from the [documentation](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-rabbitmq.html#plugins-inputs-rabbitmq-codec). Feed the rabbitmq with plain message will give a "json parse error".

**Comment by khba** [comment]
Yes I confirm, had the same issue: feed the input with bulk messages and they were being modified without me knowing why. It's because the default codec is json and that was messing with my data, instead of plain that would have just let it plain.  Now that I changed it to "plain" it's working fine.

**Comment by yaauie** [comment]
It looks like this was resolved some time ago, so I am closing.
