### ISSUE TITLE
Docs about 'host' parameter is wrong. `port` parameter ignored. Error returned when timeout is also wrong.

### ISSUE THREAD

**Issue by Erni** [logstash-plugins/logstash-input-rabbitmq#115]
When connecting to a remote AMQP server, the configuration explained in the docs is not working.
 - The `host` setting must be populated by the pair `host:port`
 - The `port` setting is completely ignored.
 - If the connection is via `HTTPS` then the `ssl` setting should be set to true. This is not wrong but not well documented.

Moreover, when the plugin cannot connect to the server (because any of the parameters are wrong or any other issue) and times out, you get the following error:
```
RabbitMQ connection error, will retry. {:error_message=>"Connection to localhost:5672 refused", :exception=>"MarchHare::ConnectionRefused"}
```
which is completely **false** and misleading.

**Comment by zargario** [comment]
@Erni 
Hi. Did you manage to find a workaround?

**Comment by nurettin** [comment]
Thank you, this worked for me.

**Comment by yaauie** [comment]
A fix in upstream connection mixin (https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/commit/447b41f823c913cc425068e2d781cae70bb02a3e) was unfortunately not ever consumed by this stand-alone plugin.

Since development of this plugin is now continuing as a part of the RabbitMQ Integration Plugin, I have opened a PR there to absorb the fix in future releases; please feel free to comment about your backport requirements if you aren't running Logstash 6.5+ (which is required for Integration Plugins):

https://github.com/logstash-plugins/logstash-integration-rabbitmq/pull/12
