### ISSUE TITLE
"java.lang.OutOfMemoryError: Java heap space" when using rabbitmq input (march_hare variant) with ack => false

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-input-rabbitmq#17]
From https://logstash.jira.com/browse/LOGSTASH-2278

**Comment by Alykoff** [comment]
I have this problem.

**Comment by jsvd** [comment]
@michaelklishin question: when a queue does a subscribe_with with auto_ack=true and a BlockingCallbackConsumer that blocks frequently, then it's necessary to limit the queue sized (through :buffer_size) because prefetch_size won't prevent the consumer to retrieve millions (2^31-1) of messages from the rabbitmq queue and blow up memory, right?

**Comment by michaelklishin** [comment]
@jsvd `basic.qos prefetch size` is exactly what limits the number of deliveries to a consumer but only if it uses manual acknowledgements. `:buffer_size` in combination with TCP back pressure in recent Java client releases can do a similar thing with automatic acknowledgements but we only consider it to be a protection measure for complete beginners.

Auto-deletion has nothing to do with this.

**Comment by michaelklishin** [comment]
`:buffer_size` controls max size of an `ArrayBlockingQueue` which deliveries are placed on.

**Comment by jsvd** [comment]
since logstash-plugins/logstash-input-rabbitmq#73, version 4.0.0 of the plugin, it directly controls the buffering queue of the rabbitmq subscriber, and it is limited to `@prefetch_size`

so essentially upgrading to this version eliminates this scenario.

That said, manual acks and prefetch size should be the default mechanism for qos

**Comment by michaelklishin** [comment]
@jsvd FYI https://github.com/rabbitmq/rabbitmq-java-client/issues/19. Using manual acks by default is a good idea nonetheless.
