### ISSUE TITLE
Rabbit credentials from file

### ISSUE THREAD

**Issue by flaiming** [logstash-plugins/logstash-input-rabbitmq#18]
We have single configuration file for each environment (dev, test, production) and that raises an issue with setting different rabbit credentials (username, password) for each environment. 
Could be possible to add new parameter to this input plugin "AuthFile", which would contain path to file with rabbit credentials? It should look like just like at logstash collectd input plugin http://logstash.net/docs/1.4.2/inputs/collectd#authfile

And same should be added to rabbitmq output plugin.

**Comment by michaelklishin** [comment]
@flaiming your idea makes sense to me. Feel free to look into this and submit a pull request. This shouldn't be too difficult to implement.

I'd recommend using a YAML or JSON file. This can go beyond storing the credentials (that's why using the same option structure as Bunny/March Hare do seems like a good idea to me).

**Comment by andrewvc** [comment]
@flaiming this isn't something we generally support in Logstash. We may merge this soon which would help in another way: https://github.com/elastic/logstash/pull/4710

**Comment by fbaligand** [comment]
@flaiming 
'environment variable injection in logstash plugin configuration' (https://github.com/elastic/logstash/pull/4710) has just been merged and will be included in Logstash 2.3.0.
I think it could answer your need.
